name: decimus
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.12.0
  flutter_multi_formatter: ^2.13.7
  intl: ^0.20.2
  uuid: ^4.5.1
  google_fonts: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0
  flutter_spinkit: ^5.2.0


flutter:

  
  uses-material-design: true

 
  assets:
     - assets/images/imagem1login.png
     - assets/images/tomas.png
     - assets/images/saofrancisco.png
     - assets/images/sbento.png
     - assets/images/miguel.png
     - assets/images/jesus.png
     - assets/images/coracao-de-jesus.png
     - assets/images/agostinho.png

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
