// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9QBcSyCkaOKtVUrRt_h1l29K0N0NgyM8',
    appId: '1:779459508336:web:12a24884f78791c5b25cb5',
    messagingSenderId: '779459508336',
    projectId: 'decimus-app',
    authDomain: 'decimus-app.firebaseapp.com',
    storageBucket: 'decimus-app.firebasestorage.app',
    measurementId: 'G-PGQ58H3GRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYXHrs2vSZdlVM4VuIMbm7dSuqzTas4Q0',
    appId: '1:779459508336:android:9669568c3143d976b25cb5',
    messagingSenderId: '779459508336',
    projectId: 'decimus-app',
    storageBucket: 'decimus-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5N8owYvVEwHZMC-rGvED1wZwRKdoKAtg',
    appId: '1:779459508336:ios:74b6b4a8e42750cbb25cb5',
    messagingSenderId: '779459508336',
    projectId: 'decimus-app',
    storageBucket: 'decimus-app.firebasestorage.app',
    iosBundleId: 'com.example.decimus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5N8owYvVEwHZMC-rGvED1wZwRKdoKAtg',
    appId: '1:779459508336:ios:74b6b4a8e42750cbb25cb5',
    messagingSenderId: '779459508336',
    projectId: 'decimus-app',
    storageBucket: 'decimus-app.firebasestorage.app',
    iosBundleId: 'com.example.decimus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9QBcSyCkaOKtVUrRt_h1l29K0N0NgyM8',
    appId: '1:779459508336:web:df21d0e6b60d95aeb25cb5',
    messagingSenderId: '779459508336',
    projectId: 'decimus-app',
    authDomain: 'decimus-app.firebaseapp.com',
    storageBucket: 'decimus-app.firebasestorage.app',
    measurementId: 'G-7ZNQQ8VLL3',
  );
}
